import os

MAX_FIRST_NAME_LENGTH = 50
MIN_FIRST_NAME_LENGTH = 3
MAX_LAST_NAME_LENGTH = 50
MIN_LAST_NAME_LENGTH = 3

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128

PASSWORD_HASH_LENGTH = 255
MAX_EMAIL_LENGTH = 255
MAX_NAME_LENGTH = 50

ACCESS_TOKEN_EXPIRE_TIME_DAYS = 30
AUTH_ALGORITHM = "HS256"

AUTH_SECRET_KEY = os.getenv("AUTH_SECRET_KEY")

if AUTH_SECRET_KEY is None:
    raise TypeError("Auth secret cannot be None.")
